config/routes.rb
Rails.application.routes.draw do

  # 利用者
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#about'
    get 'top' => 'homes#top'
    get "search" => "searches#search"
    resources :myshops
    resources :user, only: [:index]
    resource :users, only: [:show] do
      patch 'out'
    end
    resources :recipes, only: [:show] do
      resources :recipe_comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      resource :reviews, only: [:create]
    end
    get 'bookmarks' => 'bookmarks#index'
    get 'reviews' => 'reviews#index'
    get "search_bookmark" => 'bookmarks#search_bookmark'
  end

  # 管理者
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:show,:edit,:update]
    resources :homes, only: [:destroy]
    get 'top' => 'homes#top'
    get "search_comment" => "homes#search_comment"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @comments = RecipeComment.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def search_comment
    unless params[:word].blank?
      @results = RecipeComment.where('comment LIKE ?', "%#{params[:word]}%")
      results_array = RecipeComment.where('comment LIKE ?', "%#{params[:word]}%")
      @results = Kaminari.paginate_array(results_array).page(params[:page]).per(20)
    else
      @results = []
    end
  end
  
  def destroy
    @comments = RecipeComment.page(params[:page]).per(10)
    comment = RecipeComment.find(params[:id])
    comment.destroy
  end
  
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/_comment_index.html.erb
<thead>
  <tr>
    <th>レシピ</th>
    <th>コメント</th>
    <th>コメント日時</th>
    <th>コメント者</th>
    <th>削除しますか？</th>
  </tr>
</thead>
<tbody>
  <% comments.each do |recipe_comment| %>
    <tr>
      <td>
        <%= link_to recipe_path(recipe_comment.recipe_id) do %>
          <%= recipe_comment.recipe.recipe_title.truncate(10) %>
        <% end %>
      </td>
      <td><%= recipe_comment.comment %></td>
      <td><%= recipe_comment.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H時%M分") %></td>
      <td>
        <%= link_to admin_user_path(recipe_comment.user.id) do %>
          <%= recipe_comment.user.nickname %>
        <% end %>
      </td>
      <td><%= link_to "削除", admin_home_path(recipe_comment.id), method: :delete, remote: true, class: "btn btn-danger pull-right commentdelete" %></td>
    </tr>
  <% end %>
</tbody>

app/views/admin/homes/_search-form.html.erb
<div class="row mb-4">
  <div class="col-md-6 mx-auto">
    <%= form_with url: admin_search_comment_path, method: :get do |f| %>
      <%= f.label :word, '検索したいワードを入力してください' %>
      <div class="form-group">
        <%= f.text_field :word, class: 'form-control' %>
      </div>
      <div class="row">
        <div class="col-md-6 mx-auto">
          <%= f.submit '検索', class: 'btn btn-outline-secondary btn-block loading' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/homes/destroy.js.erb
$('#comment-delete').html("<%= j(render 'admin/homes/comment_index', comments: @comments) %>")

app/views/admin/homes/search_comment.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="col-6">
        <h3 class="p-3">コメント検索結果</h3>
      </div>

      <%= render "admin/homes/search-form" %>
    
      <div class="row">
        <% unless @results.blank? %>
          <table class="table table-hover" id="comment-delete">
            <%= render 'admin/homes/comment_index', comments: @results %>
          </table>
          <div class="justify-content-center text-center">
            <%= paginate @results %>
          </div>
        <% else %>
          該当するコメントはありませんでした
        <% end %>
      </div>
      
   </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="col-6">
        <h3 class="p-3">新着コメント一覧</h3>
      </div>
      <% if @comments.blank? %>
        新着コメントはありません
      <% else %> 
      <%= render "admin/homes/search-form" %>
      <table class="table table-hover" id="comment-delete">
        <%= render 'admin/homes/comment_index', comments: @comments %>
      </table>
      <% end %>
    </div>
  </div>
  <div class="justify-content-center text-center">
    <%= paginate @comments %>
  </div>
</div>