config/routes.rb
Rails.application.routes.draw do

  # 利用者
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#about'
    get 'top' => 'homes#top'
    get "search" => "searches#search"
    resources :myshops
    resources :user, only: [:index]
    resource :users, only: [:show] do
      patch 'out'
    end
    resources :recipes, only: [:show] do
      resources :recipe_comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      resource :reviews, only: [:create]
    end
    get 'bookmarks' => 'bookmarks#index'
    get 'reviews' => 'reviews#index'
    get "search_bookmark" => 'bookmarks#search_bookmark'
  end

  # 管理者
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:show,:edit,:update]
    resources :homes, only: [:destroy]
    get 'top' => 'homes#top'
    get "search_comment" => "homes#search_comment"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#CCFFCC">
    
    <div class="container-fluid">
      <button class="navbar-toggler  ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="container">
      <h4><span class="font-weight-bold"><i class="fas fa-fish"></i>今日のごはん</span></h4>

        <div class="navbar">

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <!--ゲストユーザーの場合-->
            <% if user_signed_in? && current_user.name == "guestuser" %>
              <li><%= link_to 'サイトについて',root_path,class: 'btn btn-outline-success' %></li>
              <li><%= link_to 'マイページ',users_path,class: 'btn btn-outline-success' %></li>
              <li><%= link_to '今日のランダム', top_path, class: "btn btn-outline-success" %></li>
              <li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class: 'btn btn-outline-success' %></li>
            <!--会員の場合-->
            <% elsif user_signed_in? %>
              <li><%= link_to 'マイページ',users_path,class: 'btn btn-outline-success' %></li>
              <li><%= link_to 'My店舗一覧', myshops_path, class: "btn btn-outline-success" %></li>
              <li><%= link_to 'お気に入り一覧', bookmarks_path, class: "btn btn-outline-success" %></li>
              <li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class: 'btn btn-outline-success' %></li>
            <!--管理者の場合-->
            <% elsif admin_signed_in? %>
              <li><%= link_to 'トップページ',admin_top_path, class: 'btn btn-outline-success' %></li>
              <li><%= link_to 'ログアウト',destroy_admin_session_path, method: :delete, class: 'btn btn-outline-success' %></li>
            <!--ログインしていない状態-->
            <% else %>
              <li><%= link_to 'サイトについて',root_path,class: 'btn btn-outline-success' %></li>
              <li><%= link_to '新規登録',new_user_registration_path,class: 'btn btn-outline-success' %></li>
              <li><%= link_to 'ログイン',new_user_session_path ,class: 'btn btn-outline-success' %></li>
              <li><%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "btn btn-outline-success", method: :post %></li>
            <% end %>
            </ul>
          </div>
        </div>

    </div>
  </nav>
</header>

app/views/layouts/_loading.html.erb
<div id="loading">
  <div id="loading_box">
    <div class="loading-one animation_loading">
      <p class="loading-txt">しばしお待ちを！</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>今日のごはん</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/f0039104b0.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <i class="fas fa-check-circle"></i><span class="ml-2"><%= notice %></span>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <i class="fas fa-bullhorn"></i><span class="ml-2"><%= alert %></span>
        </div>
      <% end %>
    </main>
    <%= yield %>
  </body>
</html>